package com.lanou3g.mydazahui.greendaobean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TOP_STORIES_ENTITY".
 */
public class TopStoriesEntity {

    private String title;
    private String ga_prefix;
    private String image;
    private String type;
    private Integer id;

    public TopStoriesEntity() {
    }

    public TopStoriesEntity(String title, String ga_prefix, String image, String type, Integer id) {
        this.title = title;
        this.ga_prefix = ga_prefix;
        this.image = image;
        this.type = type;
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGa_prefix() {
        return ga_prefix;
    }

    public void setGa_prefix(String ga_prefix) {
        this.ga_prefix = ga_prefix;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

}
