package com.xyb513951.mydazahui.greendaobean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.List;

/**
 * Entity mapped to table "STORIES_ENTITY".
 */
public class StoriesEntity {

    private String title;
    private String ga_prefix;
    private String multipic;
    private String type;
    private Integer id;
    private List<String> images;

    public StoriesEntity() {
    }

    public StoriesEntity(String title, String ga_prefix, String multipic, String type, Integer id) {
        this.title = title;
        this.ga_prefix = ga_prefix;
        this.multipic = multipic;
        this.type = type;
        this.id = id;
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGa_prefix() {
        return ga_prefix;
    }

    public void setGa_prefix(String ga_prefix) {
        this.ga_prefix = ga_prefix;
    }

    public String getMultipic() {
        return multipic;
    }

    public void setMultipic(String multipic) {
        this.multipic = multipic;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

}
